language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 36766266e0f1834997de90e358ea07873eccb07006f9efb7369c35823024481c
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
cache:
  directories:
    - node_modules
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
